name: dart_test_matchers
version: 0.1.0
description: Useful test matchers that are not available in the standard Dart test package.
homepage: https://github.com/matthew-carroll/dart_test_matchers

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  test: ^1.0.0

dev_dependencies:

